server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajy3600@gmail.com
    password: jflk ojgy rhgb linj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

weather:
  api:
    key: "test-weather-api-key"